### ISSUE TITLE
Actualización de dependencias indirectas

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-backend#284]
## Descripción
Encontrar la forma de actualizar dependencias indirectas con yarn, algo similar a cuando se ejecuta `npm audit fix`.

Algunas opciones son:
- [yarn-audit-fix](https://www.npmjs.com/package/yarn-audit-fix)
- Dependabot
- [Snyk](https://snyk.io/)
- [Reolutions](https://yarnpkg.com/configuration/manifest#resolutions) (puede funcionar para algunas, aunque no sé si esto implicaría instalar el paquete directamente, ni tampoco cuánto tiempo deberíamos mantenerlo ahí)

### Consideraciones
Estimar esta tarea como una ventana del tiempo que se considere se le debería dedicar

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-backend/284?planning-poker) with ZenHub @alegnaaived @cazapatamar @danflop @Trjegul84

**Comment by cazapatamar** [comment]
Se agrega la libreria `yarn-audit-fix` la cual permite automatizar el proceso de actualización de dependencias indirectas.

una vez agregada la librería, esta se ejecuta de la siguiente forma:

`yarn yarn-audit-fix`

Para garantizar que no se rompe la aplicación se recomienda ejecutar un `yarn install`. Tanto en el back como en el front fue exitoso este proceso. Si bien las alertas disminuyeron considerablemente, aún quedan algunas que van a ser tratadas posteriormente y si definitivamente no se puede entonces se dejarán ahi. 

En el back queda una alerta que parece estar relacionada con `api-doc` y que en el futuro puede ser solucionada actuaizando esta libreria.

![imagen.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/db1da695-b21e-4b2f-9eb7-8adc1f25b4d8)

En el front quedan 10 alertas (habían 19) y se espera que con la actualización de `react-scripts` varias o todas estas alertas se solucionen.

├─ ansi-html: 0.0.7
│  ├─ Issue: Uncontrolled Resource Consumption in ansi-html
│  ├─ URL: https://github.com/advisories/GHSA-whgm-jr23-g3j9
│  ├─ Severity: high
│  ├─ Vulnerable Versions: <=0.0.7
│  ├─ Patched Versions: <0.0.0
│  ├─ Via: react-scripts
│  └─ Recommendation: None
│
├─ ansi-regex: 4.1.0
│  ├─ Issue:  Inefficient Regular Expression Complexity in chalk/ansi-regex
│  ├─ URL: https://github.com/advisories/GHSA-93q8-gq69-wqmw
│  ├─ Severity: moderate
│  ├─ Vulnerable Versions: >2.1.1 <5.0.1
│  ├─ Patched Versions: >=5.0.1
│  ├─ Via: eslint, cbm-dashboard, react-scripts
│  └─ Recommendation: Upgrade to version 5.0.1 or later
│
├─ browserslist: 4.14.2
│  ├─ Issue: Regular Expression Denial of Service in browserslist
│  ├─ URL: https://github.com/advisories/GHSA-w8qv-6jwh-64r5
│  ├─ Severity: moderate
│  ├─ Vulnerable Versions: >=4.0.0 <4.16.5
│  ├─ Patched Versions: >=4.16.5
│  ├─ Via: cbm-dashboard
│  └─ Recommendation: Upgrade to version 4.16.5 or later
│
├─ glob-parent: 3.1.0
│  ├─ Issue: Regular expression denial of service
│  ├─ URL: https://github.com/advisories/GHSA-ww39-953v-wcq6
│  ├─ Severity: high
│  ├─ Vulnerable Versions: <5.1.2
│  ├─ Patched Versions: >=5.1.2
│  ├─ Via: eslint, cbm-dashboard, react-scripts
│  └─ Recommendation: Upgrade to version 5.1.2 or later
│
├─ immer: 8.0.1
│  ├─ Issue: Prototype Pollution in immer
│  ├─ URL: https://github.com/advisories/GHSA-33f9-j839-rf8h
│  ├─ Severity: critical
│  ├─ Vulnerable Versions: <9.0.6
│  ├─ Patched Versions: >=9.0.6
│  ├─ Via: react-scripts
│  └─ Recommendation: Upgrade to version 9.0.6 or later
│
├─ json-schema: 0.2.3
│  ├─ Issue: json-schema is vulnerable to Prototype Pollution
│  ├─ URL: https://github.com/advisories/GHSA-896r-f27r-55mw
│  ├─ Severity: moderate
│  ├─ Vulnerable Versions: <0.4.0
│  ├─ Patched Versions: >=0.4.0
│  ├─ Via: react-scripts, cbm-dashboard
│  └─ Recommendation: Upgrade to version 0.4.0 or later
│
├─ node-forge: 0.10.0
│  ├─ Issue: Open Redirect in node-forge
│  ├─ URL: https://github.com/advisories/GHSA-8fr3-hfg3-gpgp
│  ├─ Severity: moderate
│  ├─ Vulnerable Versions: <1.0.0
│  ├─ Patched Versions: >=1.0.0
│  ├─ Via: cbm-dashboard, react-scripts
│  └─ Recommendation: Upgrade to version 1.0.0 or later
│
├─ nth-check: 1.0.2
│  ├─ Issue: Inefficient Regular Expression Complexity in nth-check
│  ├─ URL: https://github.com/advisories/GHSA-rp65-9cf3-cjxr
│  ├─ Severity: moderate
│  ├─ Vulnerable Versions: <2.0.1
│  ├─ Patched Versions: >=2.0.1
│  ├─ Via: cbm-dashboard
│  └─ Recommendation: Upgrade to version 2.0.1 or later
│
├─ postcss: 7.0.21
│  ├─ Issue: Regular Expression Denial of Service in postcss
│  ├─ URL: https://github.com/advisories/GHSA-566m-qj78-rww5
│  ├─ Severity: moderate
│  ├─ Vulnerable Versions: <8.2.13
│  ├─ Patched Versions: >=8.2.13
│  ├─ Via: cbm-dashboard, react-scripts
│  └─ Recommendation: Upgrade to version 8.2.13 or later
│
└─ tar: 6.1.2
   ├─ Issue: Arbitrary File Creation/Overwrite via insufficient symlink protection due to directory cache poisoning using symbolic links
   ├─ URL: https://github.com/advisories/GHSA-9r2w-394v-53qc
   ├─ Severity: high
   ├─ Vulnerable Versions: >=6.0.0 <6.1.7
   ├─ Patched Versions: >=6.1.7
   ├─ Via: react-scripts, cbm-dashboard
   └─ Recommendation: Upgrade to version 6.1.7 or later

 A manera de prueba se usó la opción `yarn yarn-audit-fix --force` la cual funciona y deja únicamente 2 alertas de seguridad pero al ejecutar `yarn install` se rompe la aplicación por una dependencia llamada `postcss`. Se espera igualmente que con la actualización de `react-scripts` se pueda solucionar este problema de tal manera de poder usar el force y disminuir aún mas las alertas.
